<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>

    <ApplicationManifest>app.manifest</ApplicationManifest>

    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

    <AssemblyName>RealEstateInstallmentsManager</AssemblyName>
    <Product>المسار الذهبي</Product>
    <Title>المسار الذهبي</Title>

    <ApplicationIcon>Assets/app.ico</ApplicationIcon>
    <AvaloniaApplicationIcon>Assets/app.icns</AvaloniaApplicationIcon>

    <Version>1.0.27</Version>
    <AssemblyVersion>1.0.27.0</AssemblyVersion>
    <FileVersion>1.0.27.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.11" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.11" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.11">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" Version="2.0.0-rc6.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.2" />
    <PackageReference Include="QuestPDF" Version="2025.12.3" />
    <PackageReference Include="supabase-csharp" Version="0.16.2" />
    <PackageReference Include="Velopack" Version="0.0.1298" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="RealState\Views\ContractsViewRealEstate.axaml.cs">
      <DependentUpon>InstallmentContractsView.axaml</DependentUpon>
    </Compile>
    <Compile Update="RealState\Views\OwnersViewRealEstate.axaml.cs">
      <DependentUpon>InstallmentOwnersView.axaml</DependentUpon>
    </Compile>
    <Compile Update="RealState\Views\DashboardViewRealEstate.axaml.cs">
      <DependentUpon>InstallmentDashboardView.axaml</DependentUpon>
    </Compile>
    <Compile Update="RealState\Views\OwnersWindowViewRealEstate.axaml.cs">
      <DependentUpon>InstallmentOwnersWindowView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Installment\Views\ReceiptWindowViewInstallment.axaml.cs">
      <DependentUpon>ReceiptWindowViewInstallment.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
